services:
  lolnotifier:
    build: .
    env_file:
      - .env
    volumes:
      - lolnotifier_data:/app/data
      - lolnotifier_logs:/app/logs
    restart: unless-stopped
    command: python main.py

volumes:
  lolnotifier_data:
  lolnotifier_logs:
